import "./globals.css";
import "react-quill/dist/quill.snow.css";
import RegisterDokter3 from "./register-dokter/page3";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         {/* <body>{children}</body> */}
         <RegisterDokter3/>
      </html>
   );
}
